spring:
  application:
    name: goal-service
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/healthsync_goal}
    username: ${DB_USERNAME:healthsync}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: ${SERVER_PORT:8084}

# 외부 서비스 URL
services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  intelligence-service:
    url: ${INTELLIGENCE_SERVICE_URL:http://localhost:8083}

# JWT 설정
jwt:
  secret-key: ${JWT_SECRET:healthsync-secret-key-2024-very-long-secret-key}
  access-token-validity: ${JWT_ACCESS_VALIDITY:3600000}
  refresh-token-validity: ${JWT_REFRESH_VALIDITY:86400000}

# 로깅 설정
logging:
  level:
    com.healthsync.goal: ${LOG_LEVEL:INFO}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
